[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["setuptools", "wheel"]

[tool.poetry]
name = "crim intervals streamlit"
version = "0.1.0"
description = "Streamlit App for the CRIM Intervals Tools"
authors = ["Richard Freedman <rfreedma@haverford.edu>"]
license = "creative commons"

[[tool.poetry.source]]
name = "intervals"
url = "git+https://github.com/HCDigitalScholarship/intervals.git@rich_streamlit_dev"
priority = "primary"

[tool.poetry.dependencies]
altair = "4.2.0"
certifi = "2020.12.5"
chardet = "^4.0.0"
h11 = "0.12.0"
httpcore = "0.13.2"
httpx = "0.18.1"
idna = "3.1"
intervals = "0.3.3"
ipython = "8.4.0"
ipywidgets = "7.6.3"
joblib = "1.0.1"
jsonschema = "3.2"
lxml = "4.7.1"
matplotlib = "3.5.3"
more-itertools = "8.7.0"
music21 = "7.1.0"
numpy = "^1.22.1"
pandas = "^1.3.3"
plotly = "5.11.0"
python = ">=3.7.1,<4.0"
python-dateutil = "^2.8.2"
python-louvain = "0.16"
pytz = "2021.1"
pyvis = "0.1.9"
requests = "2.27.0"
rfc3986 = "1.4.0"
seaborn = "0.11.2"
six = "1.15.0"





[tool.poetry.dev-dependencies]

