ROM python:3.10-slim

# Install Poetry
RUN pip install poetry==1.4.2

# Set working directory
WORKDIR /app

# Copy pyproject.toml and poetry.lock
COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN poetry export -f requirements.txt > requirements.txt && \
    pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port (if needed)
EXPOSE 8000

# Run command
CMD ["python", "app.py"]

# Copy local files
COPY . .

# Expose port and set health check
EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health
# Set default command
CMD ["streamlit", "run", "intervals_streamlit2.py"]
