[tool.poetry]
name = "intervals-streamlit"
version = "0.1.0"
description = "streamlit app for crim intervals"
authors = ["Richard Freedman <rfreedma@haverford.edu>"]
license = "Creative Commons NC-SA"
readme = "README.md"

[tool.poetry.dependencies]
python = [">=3.7.1,<3.9.7", ">3.9.7,<4.0"]
altair = "4.2.0"
certifi = "2020.12.5"
chardet = "4.0.0"
crim_intervals = "2.0.12"
h11 = "0.12.0"
httpcore = "0.13.2"
httpx = "0.18.1"
idna = "3.1"
ipython = "8.4.0"
ipywidgets = "7.6.3"
joblib = "1.0.1"
jsonschema = "3.2.0"
lxml = "4.6.3"
matplotlib = "3.5.3"
more-itertools = "8.7.0"
music21 = "7.1.0"
numpy = ">=1.20.2"
pandas = "1.3.1"
plotly = "5.11.0"
plotly-express = "0.4.1"
python-dateutil = "2.8.2"
pytz = "2021.1"
pyvis = "0.1.9"
requests = "2.27.0"
rfc3986 = "1.4.0"
seaborn = "0.11.2"
six = "1.15.0"
sniffio = "1.2.0"
streamlit = "1.23.1"
textdistance = "4.2.1"
webcolors = "1.11.1"
xlsxwriter = "3.0.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
